version: '3.3'
services:
  php:
    image: php:8-apache
    volumes:
      - ./:/var/www/html
    expose:
      - 80
    ports:
      - 80:80
    links:
      - mysql

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: daw_db
      MYSQL_USER: xevi
      MYSQL_PASSWORD: 123456
    ports:
      - 9999:3306

  phpmyadmin:
    image: phpmyadmin:latest
    environment:
      PMA_HOST: mysql
    ports:
      - 8090:80
